logs_directory: /tmp/mimosa/
map_frame: mimosa_map
navigation_frame: mimosa_navigation
body_frame: mimosa_body

imu:
  manager:
    log_level: warn
    ts_offset: 0
    max_buffer_duration: 4
    pose_init_wait_secs: 1
    interpolation_max_ts_diff: 1 #s
    extrapolation_max_ts_diff: 0.15 #s
    acc_scale_factor: 1
  preintegration:
    acc_noise_density: 0.13886655606357616
    acc_bias_random_walk: 8.538212723310593e-05
    gyro_noise_density: 5.4380545102010436e-03
    gyro_bias_random_walk: 1.6587925152480572e-06
    integration_sigma: 0
    use_2nd_order_coriolis: false
    use_estimated_gravity: false
    gravity_magnitude: 9.82145996
    gravity_aligned_initialization: false

graph:
  manager:
    log_level: warn
    max_measurement_latency: 0.25
    smoother:
      lag: 0.5
      wildfire_threshold: 0.001
      relinearize_threshold_translation: 5.0e-3
      relinearize_threshold_rotation: 1.75e-2
      relinearize_threshold_velocity: 5.0e-2
      relinearize_threshold_bias_acc: 1.0e-1
      relinearize_threshold_bias_gyro: 1.0e-1
      relinearize_threshold_gravity: 1.0e-2
      relinearize_skip: 1
      enable_relinearization: true
      evaluate_nonlinear_error: false
      factorization: CHOLESKY
      cache_linearized_factors: true
      enable_detailed_results: false
      enable_partial_relinearization_check: true
      initial_position_sigma: 1.0e-6
      initial_rotation_yaw_sigma_deg: 1.0e-6
      initial_rotation_pitch_roll_sigma_deg: 1.0e-6
      initial_velocity_sigma: 1.0e-6
      initial_bias_acc_sigma: 1.0e-1
      initial_bias_gyro_sigma: 1.0e-5
      initial_gravity_sigma: 5.0e-2
      additional_update_iterations: 5

lidar:
  sensor_frame: mimosa_lidar
  T_B_S: [-0.11484, -0.01878, 0.035, 0.3799282, -0.5963678, -0.3799282, 0.5963678]
  T_B_OdometryLoggerFrame: [0, 0, 0, 0, 0, 0, 1]
  sensor_json: ../os_dummy.json
  manager:
    log_level: warn
    enabled: false
    use_to_init: false
    initial_skip: 2
    transpose_pointcloud: false
    organize_pointcloud_by_ring: true
    ts_offset: 0
    range_min: 0.35
    range_max: 100
    intensity_min: 0
    intensity_max: 1.0e+10
    ns_max: 1e8
    create_full_res_pointcloud: false
    full_res_pointcloud_publish_rate_divisor: 2
    use_reflectivity_as_intensity: false
    scale_intensity_by_sq_range: false
    near_range_correction: true
  geometric:
    log_level: warn
    enabled: false
    point_skip_divisor: 4
    ring_skip_divisor: 1
    map_keyframe_trans_thresh: 1
    map_keyframe_rot_thresh_deg: 10
    initial_clouds_to_force_map_update: 1
    lru_horizon: 1000
    neighbor_voxel_mode: 19
    scan_to_map:
      source_voxel_grid_filter_leaf_size: 1
      source_voxel_grid_min_dist_in_voxel: 0.2
      target_ivox_map_leaf_size: 1
      target_ivox_map_min_dist_in_voxel: 0.2
      num_corres_points: 5
      max_corres_distance: 1
      plane_validity_distance: 0.07
      lidar_point_noise_std_dev: 0.07
      use_huber: true
      huber_threshold: 1.345
      reg_4_dof: false
      project_on_degneneracy: false
      degen_thresh_trans: 40
      degen_thresh_rot: 0
  photometric:
    log_level: warn
    enabled: false

radar:
  sensor_frame: mimosa_radar
  T_B_S: [0.08373, 0.0213, 0.02691, 0.6830127, 0.1830128, -0.1830128, 0.6830127]
  manager:
    log_level: warn
    use_to_init: false
    enabled: false
    initial_skip: 2
    ts_offset: 0
    is_exposure_compensated: false
    range_min: 0.1
    range_max: 16
    threshold_azimuth_deg: 60
    threshold_elevation_deg: 60
    filter_min_db: 5
    frame_ms: 18.5
    huber_threshold: 1.345
    noise_sigma: 0.037527767
    outlier_threshold: 3.0

odometry:
  sensor_frame: mimosa_odometry
  T_B_S: [0, 0, 0, 0, 0, 0, 1]
  manager:
    log_level: warn
    enabled: true
    use_to_init: true
    initial_skip: 2
    ts_offset: 0
    d_opt_thresh: 1
    sigma_rot_deg: 0.5
    sigma_trans_m: 0.001
